### ISSUE TITLE
Cannot assign value type of...

### ISSUE THREAD

**Issue by PedroCavaleiro** [rushisangani/RSSelectionMenu#10]
Hi, I've recently added your lib to my project but I'm getting this error

> Cannot assign value of type '[String : Any]?' to type '[NSAttributedStringKey : Any]?'

This error can be found in the file RSSelectionMenuController.swift line 325 witch contains this function

```
    // navigation bar
    fileprivate func setNavigationBarTheme(_ theme: NavigationBarTheme) {
        if let navigationBar = self.navigationController?.navigationBar {
            
            navigationBar.barTintColor = theme.color
            if theme.color != nil {
                navigationBar.tintColor = UIColor.white
            }
            
            navigationItem.title = theme.title
            navigationBar.titleTextAttributes = theme.attributes // <- Line where the error is located (325)
        }
    }
```

**Comment by rushisangani** [comment]
Hello, @PedroCavaleiro please follow below steps.

Go to pods projects in your workspace.
Select RSSelectionMenu target.
Go to Build Settings and set Swift Language Version to 3.2

**Comment by PedroCavaleiro** [comment]
Did not know that I was able to change the Swift Language Version for only one Pod
Thanks
