### ISSUE TITLE
Request to add code to solve issue layout out of splitview area.

### ISSUE THREAD

**Issue by praditkan** [rushisangani/RSSelectionMenu#101]
Could you please add this code to fix the issue?
(_In RSSelectionMenuController, fileprivate func setTableViewFrame()_ )

When in iPad landscape with splitview.
The selection menu is out of bound of split detail view.
Due to the background.frame.size.width still got the fullscreen iPad size not the 
current split detail bound.

<img width="694" alt="Screen Shot 2020-06-08 at 12 54 30" src="https://user-images.githubusercontent.com/63773204/83996976-8e38fd00-a987-11ea-9a11-1faa35127f1e.png">

This is how I show menu.

```
if indexPath.section == 0 {
            
            switch indexPath.row {
            case 1:
                
                self.showAsFormsheet()
              
            default:
                
                break
            }
        }else{

```

And this is how I fixed it.
Please add it to your project.
```
if UIDevice.current.userInterfaceIdiom == .phone {
            print("phone")
                if UIApplication.shared.statusBarOrientation == .portrait {
                    tableViewSize = CGSize(width: backgroundView.frame.size.width - 80, height: backgroundView.frame.size.height - 260)
                    print("portrait")
                    print(tableViewSize)
                }else {
                    tableViewSize = CGSize(width: backgroundView.frame.size.width - 200, height: backgroundView.frame.size.height - 100)
                    print("landscape")
                        print(tableViewSize)
                }
            }else {
                print("iPad")
 >>>>>> self.backgroundView.frame = self.view.bounds
                tableViewSize = CGSize(width: backgroundView.frame.size.width - 300, height: backgroundView.frame.size.height - 400)
               
            }
```

Thank you.

**Comment by rushisangani** [comment]
@praditkan Can you please add a screenshot, what's the issue?
And probably the code how you're presenting the menu?

**Comment by praditkan** [comment]
I edited and added the screenshot.

I only added this line of code into your RSSelectionMenuController, and it fixed my problem.

`     self.backgroundView.frame = self.view.bounds`

**Comment by rushisangani** [comment]
@praditkan ideally any popup (formSheet) background should cover entire window width (master + detail), not only detail view.
You can take reference from iPad Settings app or alert presented on the iPad.

If we allow the user to select the item from the master view, while any popup is on the screen, then it's a bad UX because the user is expected to take any action in the popup or dismiss it.

**Comment by praditkan** [comment]
That is true in a sense of design best practice and preference.

However, your code still allow us to use this way.
Then this is still a defect, isn't it?
It displays off the screen. 

I just hope this would make it more robust to use.
I could be wrong sorry. 
I'm a new swift developer anyway.

**Comment by rushisangani** [comment]
Maybe you can present from splitViewController and then check?
`menu.show(type: <type here>, from: self.splitViewController)`

**Comment by rushisangani** [comment]
@praditkan Were you able to resolve this?

**Comment by praditkan** [comment]
Ah this one work!!! 

`menu.show(type: <type here>, from: self.splitViewController)`

Thank you so much.

**Comment by praditkan** [comment]
I found another issue.

The same project I did change self.splitViewController as you advised for those detail view.

It happens again this time within the view that is presented modally.

I tried this but it doesn't work.

`menu.show(type: <type here>, from: self.presentingViewController!)`

**Comment by rushisangani** [comment]
@praditkan why did you use `from: self.presentingViewController!` here?
I believe it's not the issue in the library. Maybe you can try presenting from another view controller or application window.

Closing this issue for now:)
