### ISSUE TITLE
In Multiselect when user select All then items should also selected

### ISSUE THREAD

**Issue by jasmit34** [rushisangani/RSSelectionMenu#102]
In Multiselect when user select All option then items should also selected. How can i achieve this? @rushisangani 

![SelectAll](https://user-images.githubusercontent.com/61501065/84359933-fafe0280-abe6-11ea-8279-10942fad2417.png)

**Comment by rushisangani** [comment]
@jasmit34  It's not in the library as of now and probably not required as well.
`Select All` is clearly understandable.

**Comment by jasmit34** [comment]
@rushisangani Thanks for your prompt reply.
I can understand you but someone not understand :). 
If possible the same thing then please help me.

**Comment by rushisangani** [comment]
probably, you can reload the table when user clicks on `Select All` but not sure if that works.

**Comment by jasmit34** [comment]
No it's not working because in code selectedItems.removeAll(). It removes all the selected items.

**Comment by rushisangani** [comment]
@jasmit34 Maybe you need to show all rows selected when the first row is 'All'. But what if the first row is `Empty`, `None`, or `Custom Text`?

It would be much more complicated to handle selection and deselection for various types.

**Comment by rushisangani** [comment]
@jasmit34 Were you able to resolve this? Did you try with another approach?

**Comment by jasmit34** [comment]
Yes i have modified the library and achieved that feature.
Thanks

**Comment by dhruvil-patel99** [comment]
> Yes i have modified the library and achieved that feature.
> Thanks

Hey may i know how you achieved this feature?
