### ISSUE TITLE
Missing Done button in 6.1.0

### ISSUE THREAD

**Issue by norbdev** [rushisangani/RSSelectionMenu#103]
RSSelectionMenu.swift line 473

```
        // add done action
        if (tableView?.selectionStyle == .multiple || !self.dismissAutomatically || style == .actionSheet)  {
            if case .actionSheet = menuPresentationStyle {
                alertController.addAction(doneAction)
            }
        }
```

**Comment by rushisangani** [comment]
@norbdev What's the issue here?
Can you elaborate?

**Comment by norbdev** [comment]
If you want an .alert not an .actionSheet the done action missing.

**Comment by pmaattanen** [comment]
The AlertAction style is set to .cancel in library. That is the reason why it doesn't show the button in iPads. when selection style is set to actionSheet (might be the case in .alert as well). Just change it to .default.

**Comment by rushisangani** [comment]
@norbdev Maybe the done button is not required in the iPad?

**Comment by norbdev** [comment]
In the 7.0.0 the issue is the same

https://github.com/rushisangani/RSSelectionMenu#presentation-style---formsheet-popover-alert-actionsheet

`// or specify alert button title`
`selectionMenu.show(style: .alert(title: "Select", action: "Done", height: nil), from: self)`

The action Done is missing. 

This commit is the issue:
https://github.com/rushisangani/RSSelectionMenu/commit/c84630e66e1f2189b4553546f914624697a8b935

**Comment by rushisangani** [comment]
@norbdev @pmaattanen Thanks for reporting the issue and supporting this library.
It's fixed now. Please update to the version `v.7.1.0`.

Thanks
