### ISSUE TITLE
How to add shadow  like highlight popover view

### ISSUE THREAD

**Issue by kirti301290** [rushisangani/RSSelectionMenu#106]
Hello 
i am using this control and it have lot of feature  but facing one problem it not  highlight  so user are not easily interact this popup control 
any want to give shadow so it highlight 
attached screenshot 
![Simulator Screen Shot - iPhone 11 - 2020-07-13 at 15 18 23](https://user-images.githubusercontent.com/10956919/87290832-22b0f500-c51c-11ea-9ee6-d27645834189.png)

**Comment by rushisangani** [comment]
Probably you don't need to show popover on click of searchbar. Instead you can filter the data directly without showing the popover.

**Comment by kirti301290** [comment]
Hello
No,in my Screenshot  need  dropdown in when click on TextField  pls help me
now is dummy data show you see similar record

**Comment by rushisangani** [comment]
@kirti301290 Are you able to solve the problem? If you show it using **popover** type then the background shadow will be automatic by the ios. You can also try using **.formsheet** or **.alert**

**Comment by kirti301290** [comment]
@rushisangani  
Thanks for reply but if i use   .formsheet or .alert then it will not point to textfield  and it show Center of uiview
i need to point to textfield that why used popover

**Comment by rushisangani** [comment]
@kirti301290 For popover background is by default by system. Maybe you can try using **.alert** with the title? then user will know what they're selecting.

**Comment by rushisangani** [comment]
@kirti301290 Let me know if that works for you. Closing this issue for now :)
