### ISSUE TITLE
In multi selection option if we have same name for 2 entries then these names selected when tap on one.

### ISSUE THREAD

**Issue by jasmit34** [rushisangani/RSSelectionMenu#107]
In multi selection option if we have same name for 2 entries then these 2 names selected when tap on one.
If i want to select 1 entry at one click, how is it possible? Is there any solution?

**Comment by rushisangani** [comment]
@jasmit34 each entry should be unique for the selection. You should only show one of them in the list.

**Comment by jasmit34** [comment]
Thanks for your prompt response. 
Yes but sometimes both users have same name so it creates issue, Let me know if any workaround.

**Comment by rushisangani** [comment]
@jasmit34 Menu accepts any type that implements `Equatable`. You should pass entier model in the list instead of passing strings array. Also your model should implement `Equatable` to uniquely identify each user.

**Comment by jasmit34** [comment]
Yes working fine. Thanks @rushisangani
