### ISSUE TITLE
Can we preselect certain options at the very first time?

### ISSUE THREAD

**Issue by pateldhruvil96** [rushisangani/RSSelectionMenu#109]
I mean if we open the selection list for the first time, then i want certain elements to be selected already. So how can we do that?
Please let me know!

**Comment by rushisangani** [comment]
@pateldhruvil96 Please pass items in selected array like below:
`selectionMenu.setSelectedItems(items: simpleSelectedArray)`

**Comment by dhruvil-patel99** [comment]
> @pateldhruvil96 Please pass items in selected array like below:
> `selectionMenu.setSelectedItems(items: simpleSelectedArray)`
> 
> Check [example](https://github.com/rushisangani/RSSelectionMenu#simple-selection-list) for more features and details.

Thanks for the info i misplaced that array my bad
