### ISSUE TITLE
`parentController` should be weak var

### ISSUE THREAD

**Issue by hstdt** [rushisangani/RSSelectionMenu#11]
Can't deinit after pushing.
![image](https://user-images.githubusercontent.com/10215098/33931793-1969067c-e02c-11e7-86da-4809f495ef01.png)

**Comment by rushisangani** [comment]
@hstdt, thanks for reporting the issue.
Please update your pod to latest version 3.0.
The issue has been resolved now.

**Comment by hstdt** [comment]
@rushisangani  It works well now. Closed.
