### ISSUE TITLE
Done button in popover

### ISSUE THREAD

**Issue by Jainesh219** [rushisangani/RSSelectionMenu#114]
Thanks for this library.

Just wanted to check is there is anyway to add done button in popover. If yes kindly guide.

Thanks again.

**Comment by rushisangani** [comment]
For single selection in Popover, done button is not needed.

For multiple selection. It will be available.

**Comment by Jainesh219** [comment]
Thanks Rushi for your prompt reply.
You mean in the new version it will be available right specifically for multiple selection popover?
