### ISSUE TITLE
Cannot assign value of type '[String : Any]?' to type '[NSAttributedStringKey : Any]?'

### ISSUE THREAD

**Issue by songcamhoi** [rushisangani/RSSelectionMenu#12]
I change in swift 4:
Go to pods projects in your workspace.
Select RSSelectionMenu target.
Go to Build Settings and set Swift Language Version to 3.2
But " Cannot assign value of type '[String : Any]?' to type '[NSAttributedStringKey : Any]?' "

**Comment by rushisangani** [comment]
Hi @songcamhoi, please update your pod to latest version **RSSelectionMenu (3.1)**
Swift 4.0 support is added now.
