### ISSUE TITLE
Issue in Formsheet

### ISSUE THREAD

**Issue by inamurrahman** [rushisangani/RSSelectionMenu#17]
Formsheet appears only one time, If the tap anywhere else or make a selection and then try to show the Formsheet it shows nothing.

**Comment by inamurrahman** [comment]
Im using the latest pod.

**Comment by rushisangani** [comment]
Hello @inamurrahman, Could you please share your code, how you're showing the menu?
I would recommend creating new selectionMenu instance every time when displaying the menu, rather than creating a global variable.

**Comment by inamurrahman** [comment]
I have figured it out, there was some logical issue in my view. Thanks for the response :)
