### ISSUE TITLE
Detect event after select an item

### ISSUE THREAD

**Issue by vicheanak** [rushisangani/RSSelectionMenu#18]
How can I detect an event after an item is selected? 

Thanks

**Comment by rushisangani** [comment]
@vicheanak , What do you want to achieve when an item is selected?

**Comment by rushisangani** [comment]
@vicheanak you can get selection event on each item selected in following method.

```
selectionMenu.setSelectedItems(items: selectedDataArray) { (text, selected, selectedItems) in
}
```
Also, you will get all selected items on menu dismissal event.
```
selectionMenu.onDismiss = { selectedItems in
  self.selectedDataArray = selectedItems
}

```
