### ISSUE TITLE
On dismiss closure feature request

### ISSUE THREAD

**Issue by heliumdice** [rushisangani/RSSelectionMenu#26]
Hey 

This pod is so so good and such a pleasure to use. Thanks for making and sharing it!

I have a feature request. Would it be possible to add an on dismiss callback closure which would be triggered when the formsheet style gets dismissed.

Thanks!

**Comment by rushisangani** [comment]
Hi, @heliumdice thanks for the wonderful suggestion.
This has been added in latest version 4.0

you can use it like below:

```
// get on dismiss event with selected items
selectionMenu.onDismiss = { selectedItems in
   self.selectedDataArray = selectedItems
}
```

optionally you can comment the line - for updating array on each selection event and you'll get final selected items on menu dismissal.

```
// show selected items
selectionMenu.setSelectedItems(items: selectedDataArray) { (text, selected, selectedItems) in
  //self.selectedDataArray = selectedItems
}
```

**Comment by heliumdice** [comment]
Oh wow that is amazing! So quick.

I implemented it today and it works a treat! 

Thanks you!
