### ISSUE TITLE
onDismiss was not found

### ISSUE THREAD

**Issue by kaitlyntier** [rushisangani/RSSelectionMenu#28]
Hi

Awesome work with RSSelectionMenu. Makes creating of drop down easier, manageable, and cool. Though I am encountering an issue when I try to use onDismiss. Swift shows an error that the menu has no member 'onDismiss'. Is there some import or configuration I am missing?

Thanks

**Comment by rushisangani** [comment]
@kaitlyntier Can you please try updating your cocoapods?
