### ISSUE TITLE
Every row mark as checked

### ISSUE THREAD

**Issue by proovek** [rushisangani/RSSelectionMenu#30]
What is my problem? - It's works perfect but when I select one row, the App shows me "one row selected... etc" and it's okay, but when im looking into an App I have "checked" every rows.

there is my code:

```
@IBAction func licenseSelection(_ sender: Any) {
                let context = licenseSavingController.persistentContainer.viewContext
                let request = NSFetchRequest<NSFetchRequestResult>(entityName: "Licencja")
            let selectionMenu = RSSelectionMenu(selectionType: .Single, dataSource: licencje, cellType: .Basic) { (cell, object, indexPath) in
                cell.tintColor = .orange

                request.returnsObjectsAsFaults = false
                do {
                    var result = try context.fetch(request) as! [NSManagedObject]
                    result = [result[indexPath.row]]
                    for data in result {
                        self.licznik = self.licznik+1
                        cell.textLabel?.text = data.value(forKey: "licenseDescript") as? String ?? data.value(forKey: "licenseURL") as? String
                        //forKey: "licenseURL") as? String ?? "default"
                        //forKey: "licenseNumber") as? String ?? "default"
                        //data.value(forKey: "deviceID") as? String ?? "default"
                    }
                } catch {
                    print("Failed")
            }
        }

            selectionMenu.uniquePropertyName = "licznik"
            selectionMenu.setSelectedItems(items: wybranaLicencja) { (text, isSelected, selectedItems) in
                self.wybranaLicencja = selectedItems
                print(selectedItems)
            }
            selectionMenu.show(style: .Popover(sourceView: sender as! UIView, size: nil), from: self)
        }

```
like that: https://imgur.com/nveTKJ8 Im really confused with this :P

**Comment by proovek** [comment]
And how I can get some values from dataCore which is selected?

**Comment by rushisangani** [comment]
Your data models must have one unique property.
Here, In your Entity **Licencja** which property has uniqueValue?
You need to set "String description of the property"

**Comment by proovek** [comment]
Every value in this entity is unique :P
for example **licenseNumber** is unique

**Comment by proovek** [comment]
Can you help me with this? Im trying sooo many times :/

**Comment by rushisangani** [comment]
Maybe you can try something like this
```
let context = licenseSavingController.persistentContainer.viewContext
        let request = NSFetchRequest<NSFetchRequestResult>(entityName: "Licencja")
        request.returnsObjectsAsFaults = false
        
        guard let result = try? context.fetch(request) as? [Licencja] else {
            return
        }
        
        let selectionMenu = RSSelectionMenu(selectionType: .Single, dataSource: result ?? [], cellType: .Basic) { (cell, object, indexPath) in
            
            let licznik = object
            cell.tintColor = .orange
            cell.textLabel?.text = licznik.licenseDescript
        }
```

**Comment by proovek** [comment]
I'll try later but thanks for some help :) Now im on outside

**Comment by proovek** [comment]
I try and it's doing the same :/ I have a problem with uniquePropertyName

**Comment by proovek** [comment]
Every marks are checked every time... it's weird

**Comment by proovek** [comment]
All my code? 
For explain - Your library works good, but my problem is here - I need to set uniquePropertyName with my License entity for example for attribute with id = "licenseNumber"
I need to recall to this id, but I couldn't get this id from dataCore

**Comment by proovek** [comment]
response from entity
[<Licencja: 0x6000002843d0> (entity: Licencja; id: 0xd000000000040000 <x-coredata://197130E8-8765-4C43-A0E1-2628597E0693/Licencja/p1> ; data: {
    deviceID = "0C4BE11B-63F5-43C5-899F-DF80F319EFD4";
    licenseDescript = "Serwer Api testowy";
    licenseNumber = "DED-3139557474104099-API";
    licenseURL = "https://someexampleAPI.com.pl/api/";
})]

what I should to use to get "id: 0xd000000..."??? I need this for a unique key and it should works

**Comment by rushisangani** [comment]
Your Entity must be subclass of NSObject.

**Comment by proovek** [comment]
that's how im sending someone to entity, 
`import Foundation
import CoreData

extension Licencja {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Licencja> {
        return NSFetchRequest<Licencja>(entityName: "Licencja")
    }
    
    @NSManaged public var licenseURL: String?
    @NSManaged public var deviceID: String?
    @NSManaged public var licenseNumber: String?
    @NSManaged public var licenseDescript: String?
}

`

it is in nsobject

**Comment by proovek** [comment]
What do you mean?
Can you write some example or something?

**Comment by proovek** [comment]
My entity is a subclasss of NSManagedObject it's the same as nsobject

**Comment by proovek** [comment]
How can I delete those little "birds" on selected?

**Comment by proovek** [comment]
Only they works badly

**Comment by rushisangani** [comment]
You need to perform following steps:

1. Implement **UniqueProperty** protocol in your **Licencja** class.
2. Return property name that has unique value.

```
func uniquePropertyName() -> String {
        return "licenseNumber"
}
```
3. Fetch your entity **Licencja** list.

`let result = <** Fetch call here **>`

4. Declare already selected items to show in menu.

`var selectedLicencja = []()`

5. Implement selection menu as follows:

```
let selectionMenu =  RSSelectionMenu(dataSource: result ?? []) { (cell, object, indexPath) in
    cell.textLabel?.text = object. licenseDescript
 }

selectionMenu.setSelectedItems(items: selectedLicencja) { (text, isSelected, selectedItems) in

    // update your existing array with updated selected items, so when menu presents second time updated items will be default selected.
    self.selectedLicencja = selectedItems
}

// show as popover
selectionMenu.show(style: .Popover(sourceView: sender as! UIView, size: nil), from: self)
```

**Comment by proovek** [comment]
Can you tell me how to delete marks from your code?

**Comment by rushisangani** [comment]
It should work perfectly if you've configured all things properly.
I'll get idea if you share your datamodels and other files where you're showing the menu.

**Comment by proovek** [comment]
I'll sent you my project on email, I don't want to share it public right now, okay?

**Comment by rushisangani** [comment]
Can you please try updating pod with version 4.0.2 and check if it works?

**Comment by proovek** [comment]
Yea I can try

**Comment by proovek** [comment]
Now it's work fine, thanks for helping me.
