### ISSUE TITLE
[Feature Request] Add an option to show a simple title in Formsheet style

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#31]
Hello

Thanks for this awesome lib. Works great. Anyways, I was wondering if you could allow showing a simple title at the top of the selection menu when its style is `.Formsheet`, basically above the search bar (if it's enabled) or where the search bar would be

Thanks in advance 😀🙌🏼

**Comment by rushisangani** [comment]
Please upgrade to the latest version **5.1** and you can use presentation style **Alert** to have a menu with the title.

**Comment by jahirfiquitiva** [comment]
@rushisangani Is it possible to use the Title and the SearchBar in `Alert` style? ... That's basically the feature request

**Comment by rushisangani** [comment]
Yes its possible
