### ISSUE TITLE
Missing selected items when using the select all first first row option

### ISSUE THREAD

**Issue by heliumdice** [rushisangani/RSSelectionMenu#33]
Hi,

Again I am loving this pod. Thanks for keeping it well maintained!! 

I think I found a bug today. 

If you add a first row with type .All. In the callback to setSelectedItem. The selected items array is returning with zero items. 

It would make sense to me if there is a select all option available the setSelectedItem closure should return an array of all the items. 

If this is not a bug and it is the intentional behaviour I am sorry. I just thought I would raise it with you.

Thanks.

**Comment by rushisangani** [comment]
Hi @heliumdice 
Thanks for the feedback.

You'll get an event when you select the first row whether it is "All", "None" or any text you've set.

```
// array of data objects
var dataArray = []

//  array of selected items
var selectedItems = []

// var to maintain first row selection
var firstRowSelected = true

selectionMenu.addFirstRowAs(rowType: .All, showSelected: firstRowSelected) { (text, isSelected) in
       firstRowSelected = isSelected
      
      // Here we'll get the text of the row and based on the text we can decide if it is none or all.
      // Ex.
     if (text == "All"){
          // do something ( selectedItems = dataArray)
     }     
}

```

I hope you got my point.
