### ISSUE TITLE
onDismis not triggered when dismissing formsheet with first row select all option highlighted 

### ISSUE THREAD

**Issue by heliumdice** [rushisangani/RSSelectionMenu#34]
Hi,

I found another bug while using the first row select all option.

If you create a formsheet with a first row as a select all option. 

The onDismiss callback does not fire. 

Thanks again for this amazing pod. :)

**Comment by rushisangani** [comment]
@heliumdice Dismiss callback will always get fired, could you please check again?

**Comment by heliumdice** [comment]
You are correct this is working.
