### ISSUE TITLE
Sticky Search bar

### ISSUE THREAD

**Issue by raeesmadathil** [rushisangani/RSSelectionMenu#36]
Thanks for such a great library, Can you please make the search bar as sticky on top while scrolling, it will possible by  adding searchbar in tableview delegate , 'tableView(_ tableView: UITableView, 
 viewForHeaderInSection section: Int) -> UIView?'  instead of 'tableHeaderView', 
Thanks for great work  💯 👍

**Comment by rushisangani** [comment]
Hi @raeesmadathil 
Thanks for the suggestion.

I've fixed this in new version 5.0.2

**Comment by raeesmadathil** [comment]
Hi @rushisangani 
Thanks for your great work
