### ISSUE TITLE
Disable cell check

### ISSUE THREAD

**Issue by najoua** [rushisangani/RSSelectionMenu#37]
Hi, 

I want to disable checking the default checked cell so that user cannot uncheck them. 
How can I do that please?

Thank you

**Comment by rushisangani** [comment]
Hi,
Can you describe what you want to achieve?

**Comment by najoua** [comment]
I have a list of customselectedDataArray, it must be checked all the time, the user shouldn't disable it anymore.

**Comment by rushisangani** [comment]
It wont be possible as of now, it would be rather you dont pass those items in to show in menu.

**Comment by najoua** [comment]
Actually I need to show them.
Thank you anyway.
