### ISSUE TITLE
Get the Id of the cell Selected?

### ISSUE THREAD

**Issue by dheeraj-appzop** [rushisangani/RSSelectionMenu#38]
Thanks for the great library.
How to get the id of the selected cell in formsheet?
The dataSource is a dictionary of key, value pairs. On cell selection how to capture the Id ? 
Any help?
Thanks.

**Comment by rushisangani** [comment]
You'll get selected items in **setSelectedItems** handler or **onDismiss** handler.
You'll get the array of dictionaries since you've passed an array of dictionaries as **DataSource**.
If there is a single selection - you'll get one selected item in handler.

Hope this helps !!

**Comment by dheeraj-appzop** [comment]
Thanks for the help.
The dataSource Actually is not a dictionary of key value pairs, It is an array of values.
How to pass dictionary of key value pairs as dataSource?
Thanks.

**Comment by rushisangani** [comment]
- You need to pass an array as datasource to the menu.
- From Dictionary only, menu can not be shown as it should have number of options to select.

**Comment by dheeraj-appzop** [comment]
If I pass array then how to get the Id of the selected element.
I want to display a name in the table view cell and get its id on selected.
How could I do that?
Thanks for the help.

**Comment by dheeraj-appzop** [comment]
Ok.Thanks.
But is it possible to do the way I am looking for using this library?
