### ISSUE TITLE
Using Present or Push disables the custom NavigationBar styles

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#40]
I want to use `.Multiple` and `.Present` at the same time. I do not want the "Done" button but a cancel button on the left. Anyways, the library keeps overriding my custom configuration.

Please give us full control of the `NavigationBar` buttons in any of the styles.
Basically, disable [these checks](https://github.com/rushisangani/RSSelectionMenu/blob/fa6367b575f02d758f91d65e7fefd5ad0ff446ec/RSSelectionMenu/RSSelectionMenu/Source/RSSelectionMenuController.swift#L284), please.

Thanks

**Comment by rushisangani** [comment]
@jahirfiquitiva,
How would you dismiss the menu, if you have multiple selection and only cancel button?

**Comment by rushisangani** [comment]
@jahirfiquitiva What kind of changes you want to do on Done button clicked.
You'll get an event when menu is dismissed.

**Comment by rushisangani** [comment]
@jahirfiquitiva 
You'll get an event with selected items on menu dismiss - whether it is cancelled or dismissed.
Depending on the selected items result you can make decisions.

```
selectionMenu.onDismiss = { selectedItems in
    self.selectedDataArray = selectedItems
}
```
