### ISSUE TITLE
NavigationBar barTintColor not always working

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#41]
Hi

I am trying to set `#212121` as the `barTintColor` of the `NavigationBar` but it isn't working properly as a lighter color is set.

Look at the screenshot below: the `StatusBar` color and `SearchBar` colors are `#212121` but the `NavigationBar`'s isn't (which actually is `#323232`).

![captura de pantalla 2018-08-18 a la s 18 06 43](https://user-images.githubusercontent.com/10360816/44303917-a9e69580-a312-11e8-8227-a86695983082.png)

**Comment by rushisangani** [comment]
@jahirfiquitiva 
Upgrade to the latest version 5.0.3.
You'll get an access for navigationBar -> `menu.navigationBar`

**Note:** To modify navigationBar you should use it in willAppear.
```
menu.onWillAppear = {
 menu.navigationBar =
}
```

**Comment by jahirfiquitiva** [comment]
Hey @rushisangani 

I just implemented this and the `navigationBar` is now themed properly, but for some reason, a weird margin/space appears between the `navigationBar` and the `searchBar`

![captura de pantalla 2018-08-21 a la s 11 11 58](https://user-images.githubusercontent.com/10360816/44414354-2c4da000-a533-11e8-8de9-5dcef6c6c80e.png)

**Comment by rushisangani** [comment]
Could you please share your code?

**Comment by jahirfiquitiva** [comment]
Here's the code to change the color:
```swift
selectionMenu.onWillAppear = {
	selectionMenu.navigationBar?.isTranslucent = false
	selectionMenu.navigationBar?.backgroundColor = Theme.primaryColor()
	selectionMenu.navigationBar?.barTintColor = Theme.primaryColor()
}
```

The issue only happens when adding `selectionMenu.navigationBar?.isTranslucent = false` but it is required, or the `navigationBar` won't really change the color and the initial issue persists

**Comment by rushisangani** [comment]
Give me a few mins, I'll check and update.

**Comment by jahirfiquitiva** [comment]
Thank you so much! 😀 @rushisangani

**Comment by rushisangani** [comment]
This is only happening in **style = Present** and **selectionMenu.navigationBar?.isTranslucent = false**
It's weird..

**Comment by rushisangani** [comment]
@jahirfiquitiva 
Navigation bar blank space issue solved. - Please upgrade to version 5.1.1
