### ISSUE TITLE
Allow changing the color of SearchBar field background and text

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#42]
As you can see in the screenshot below, the `SearchBar` is white and text is light gray, but I would like to give it custom colors.

Unfortunately, the `SearchBar` is a private field and I can't seem to find a way to customize it as I want to.

Thanks

![captura de pantalla 2018-08-18 a la s 18 06 43](https://user-images.githubusercontent.com/10360816/44303926-e914e680-a312-11e8-8487-dad92ecd598f.png)

**Comment by rushisangani** [comment]
@jahirfiquitiva 
Upgrade to the latest version **5.0.3** & You'll get an access for SearchBar `menu.searchBar`

**Comment by tapizquent** [comment]
How did you manage to change the background of the searchBar?

I have been trying but without luck.
I need to change the white background you see on that picture @jahirfiquitiva posted and the text to a different color too
