### ISSUE TITLE
Selection issues in v 5.1

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#43]
Hey

After updating to latest version, I'm facing an issue where selection of some items in table does not work.

It's happening in `Single` and `Multiple` selection types as well. And without custom cells too.

Here's a gif showing the issue:

![kapture 2018-08-21 at 11 47 27](https://user-images.githubusercontent.com/10360816/44416289-28704c80-a538-11e8-8bc3-7c047be49864.gif)

**Comment by rushisangani** [comment]
Can you run the example code?
It's may be issue with your selectedDataSource.

**Comment by jahirfiquitiva** [comment]
@rushisangani 
The example code works fine, but my code worked fine with previous versions so I don't know what could have changed in the library for it to stop working

**Comment by rushisangani** [comment]
@jahirfiquitiva 
Is this resolved?

**Comment by jahirfiquitiva** [comment]
No, it isn't resolved
As I told you, my code worked fine in previous versions of the library. I don't see any reasons why it shouldn't work in the latest one.

**Comment by rushisangani** [comment]
I've made a special demo for you, with all the features implemented using **version 5.1.1**
Kindly refer to this.
[RSSelectionMenuDemo.zip](Demo)
It's working fine with all presentation styles.

**Comment by jahirfiquitiva** [comment]
@rushisangani 
Thanks but I don't see anything special in that demo that is different from the examples in README ... Have you tried to make it work with custom objects/models or even an array of `Int`s ?

**Comment by rushisangani** [comment]
@jahirfiquitiva 
The same example has been updated with the custom models.

You can download from here.
[RSSelectionMenuDemo.zip](https://github.com/rushisangani/RSSelectionMenu/files/2313033/RSSelectionMenuDemo.zip)

Kindly check the issue from your end.
