### ISSUE TITLE
cancell button

### ISSUE THREAD

**Issue by Amirnajafi** [rushisangani/RSSelectionMenu#5]
first i want to thanks for your very good support 
thanks to add function to add title but very little thing still has problem for me 
when i add search button i can change the placeholder of search that is awesome but there is a 
cancell buttun with text "Cancell" its whould be nice if you can add this function to 

by the way you are so cool man !!!

**Comment by rushisangani** [comment]
Thanks.
Please give a star if you like RSSelectionMenu.

You can now customize cancel button as well.
Update your pod to version 2.0.7

// set cancel button title and tint color.

selectionMenu.searchBarCancelButtonAttributes = ("Dismiss", UIColor.darkGray)
or
selectionMenu.searchBarCancelButtonAttributes = ("Dismiss", nil)
