### ISSUE TITLE
Clear Selection Button

### ISSUE THREAD

**Issue by neXus1987** [rushisangani/RSSelectionMenu#50]
Hi,

this is a really great swift module!

Is it possible to have a button e.g. on the left navbar for clearing the selection?

Thanks
Phil

**Comment by rushisangani** [comment]
Hello @neXus1987 
to clear the selection you should use the following with option (**Empty** or **None**)

```
selectionMenu.addFirstRowAs(rowType: .Empty, showSelected: self.firstRowSelected) { (text, isSelected) in
    
    // update your flag here to maintain consistency. -  This is required to be updated when presenting for the second time.
    self.firstRowSelected = isSelected
}
```
