### ISSUE TITLE
what is correct version to install ?

### ISSUE THREAD

**Issue by d33pak-s1ngh** [rushisangani/RSSelectionMenu#52]
when i added `pod 'RSSelectionMenu' `into my podfile i got following message in terminal

`Installing RSSelectionMenu (3.3) 
`
which means it is installing 3.3

and when i addedd` pod 'RSSelectionMenu', '~> 5.2.1'` into podfile i got following message in terminal

```
CocoaPods could not find compatible versions for pod "RSSelectionMenu":
  In Podfile:
    RSSelectionMenu (~> 5.2.1)

None of your spec sources contain a spec satisfying the dependency: `RSSelectionMenu (~> 5.2.1)`.

```

Please define which is correct version to install.

**Comment by rushisangani** [comment]
@d33pak-s1ngh 
 Try to run the command pod update first

**Comment by d33pak-s1ngh** [comment]
is there way in which i can directly install latest version pod update is headache it will change many things.
Thank you for your support.

**Comment by rushisangani** [comment]
@d33pak-s1ngh 
You try
`pod update RSSelectionMenu`
