### ISSUE TITLE
Formsheet Width is not proper some time

### ISSUE THREAD

**Issue by d33pak-s1ngh** [rushisangani/RSSelectionMenu#53]
I am using formsheet to present users list which works fine but some time the width of formsheet shrink check the following image.
[screen shot](https://ibb.co/fCAJKz)

It happens only some time other time the width is fine but i am unable to find why this is happening. 
![img_0070](https://user-images.githubusercontent.com/23626544/45797684-6d68d980-bcc4-11e8-8eb7-3586c6a967a3.PNG)

**Comment by SpajicM** [comment]
Duplicate of the issue I opened almost a month ago.
https://github.com/rushisangani/RSSelectionMenu/issues/48

**Comment by rushisangani** [comment]
@d33pak-s1ngh this is fixed in version **5.3.1**
