### ISSUE TITLE
automaticDimension error after updating to 5.3

### ISSUE THREAD

**Issue by jahirfiquitiva** [rushisangani/RSSelectionMenu#54]
Hi
I'm getting error `Error:(78, 33) 'automaticDimension' has been renamed to 'UITableViewAutomaticDimension'` while compiling my app after I updated to 5.3
Can you please look into it?

**Comment by rushisangani** [comment]
@jahirfiquitiva This is due to the swift version is changed to 4.2
Can you please check in version 4.2?

You can also set swift version for specific pod only.

**Comment by rushisangani** [comment]
Hi you can change the swift version from build setting of project.

Xcode10 -> Build Setting -> Swift -> 4.2

You can also do the same with the
Pod target.

Pods project -> RSSelectionMenu -> build setting -> Swift -> 4.2

Hope this helps ☺️
