### ISSUE TITLE
search bar in navigation bar

### ISSUE THREAD

**Issue by AhmadOdeh93** [rushisangani/RSSelectionMenu#55]
Hello 

any way to add serach bar in Navigation bar ?

**Comment by rushisangani** [comment]
@AhmadOdeh93 as per the current implementation of filtering and searching data, search bar on navigationBar is not possible, because it would be only available for **Present** and **Push** style.

**Comment by AhmadOdeh93** [comment]
@rushisangani , thank you , but no any way fix it or edit on it ?
