### ISSUE TITLE
Popover with Title

### ISSUE THREAD

**Issue by phr85** [rushisangani/RSSelectionMenu#56]
Hi folks
Is there a way to show "Popover" with a NavigationBar or at least a custom Title?
I saw the screenshot in this ticket: https://github.com/rushisangani/RSSelectionMenu/pull/51
This would be exactly what I need.

Bests

Philippe

**Comment by phr85** [comment]
@rushisangani  thank you for the quick fix & answer! 🙏🏻

**Comment by rushisangani** [comment]
@phr85 upgrade to 5.3.2 and you can set title by setting navigationBar theme.
