### ISSUE TITLE
Default Selection

### ISSUE THREAD

**Issue by fcbmojtaba1995** [rushisangani/RSSelectionMenu#57]
Thank for library.
How to set item default selected in single selection?

**Comment by fcbmojtaba1995** [comment]
Can you give an example?

**Comment by rushisangani** [comment]
@fcbmojtaba1995 

`
// set default selected items when menu present on screen.
// Here you'll get onDidSelectRow

selectionMenu.setSelectedItems(items: simpleSelectedArray) { (text, isSelected, selectedItems) in
    
// update your existing array with updated selected items, so when menu presents second time updated items will be default selected.
    self.simpleSelectedArray = selectedItems
}
`

see example for more details.
