### ISSUE TITLE
Error while creating menu

### ISSUE THREAD

**Issue by ControlAdad** [rushisangani/RSSelectionMenu#6]
let selectionMenu =  RSSelectionMenu(dataSource: simpleDataArray) { (cell, object, indexPath) in
            cell.textLabel?.text = object
        }

When I try to create a menu using code above, compiler give this error:

![image](https://user-images.githubusercontent.com/179375/31953123-3d2aeef4-b8ef-11e7-9158-ca01a0f74d97.png)

**Comment by rushisangani** [comment]
Have you tried with latest pod version 2.0.7?
- Please install the latest version if not.

If you're using swift 4 project and installing RSSelectionMenu then please follow following steps.

1. Go to pods projects in your workspace.
2. Select RSSelectionMenu target.
3. Go to Build Settings and set Swift Language Version to 3.2

Cheers.
