### ISSUE TITLE
Empty tableView message

### ISSUE THREAD

**Issue by aryan-smartsense** [rushisangani/RSSelectionMenu#60]
I would like to show a UILabel with a message when the datasource is empty to handle empty tableView. How is it possible here?

**Comment by rushisangani** [comment]
Try this one. If it would be ok.

```
selectionMenu.addFirstRowAs(rowType: .Custom(value: "No data found"), showSelected: false)
 { (text, selected) in
 }       
```
<img width="292" alt="screen shot 2018-11-16 at 9 50 38 pm" src="https://user-images.githubusercontent.com/7363933/48633605-b221a000-e9e9-11e8-89e5-4adb4fe24227.png">

**Comment by rushisangani** [comment]
@aryan-smartsense did this work for you?

**Comment by rushisangani** [comment]
@aryan-smartsense update to the latest version 6.0 and you can set empty data message.

```
menu.showEmptyDataLabel()
//or 
menu.showEmptyDataLabel(text: "No players found")
```
