### ISSUE TITLE
how to get subtitle value in selectionMenu.onDismiss

### ISSUE THREAD

**Issue by isaacraja15** [rushisangani/RSSelectionMenu#62]
hi sir,

Im trying multiselect Actionsheet in that how can i get subtitle value in ondismiss?

![screenshot 2018-11-23 at 1 00 11 am](https://user-images.githubusercontent.com/44321070/48919906-a63b4f80-eebb-11e8-9c9d-20def25d581d.png)

**Comment by rushisangani** [comment]
@isaacraja15 You will get all selected objects( Array of Strings, Int, Struct, Class etc.) on menu dismiss.

You can extract the required information from that data.
it's like same data you passed to the menu but with only selected items.

Hope this helps.
