### ISSUE TITLE
[Question?] Bring RSSelectionMenu to top of all view?

### ISSUE THREAD

**Issue by hangocanh2303** [rushisangani/RSSelectionMenu#63]
How to bring RSSelectionMenu to top of all view ?

**Comment by rushisangani** [comment]
@hangocanh2303 try to present it from window's rootViewController.

`(UIApplication.shared.delegate as! AppDelegate).window?.rootViewController`

**Comment by hangocanh2303** [comment]
thank @rushisangani , last question for you. Can i change height of popover wrap content of number item?

**Comment by rushisangani** [comment]
@hangocanh2303 yes. You can set popover size(width, height)
`selectionMenu.show(style: .Popover(sourceView: sourceView, size: nil), from: self)`
