### ISSUE TITLE
[Question] Any way to implement it together with dynamic table?

### ISSUE THREAD

**Issue by martin-one** [rushisangani/RSSelectionMenu#64]
As the title says, I want to implement this whit an alrready done dynamic table in the same screen.

**Comment by rushisangani** [comment]
@martin-one can you please describe more about this feature?

**Comment by mikerz** [comment]
> @martin-one can you please describe more about this feature?

I'm wishing for this functionality as well. An example use case is a custom nib with a tableview, and having this library drive its logic without requiring that it be presented as a separate view controller. For example, a screen with a title, and a few toggle buttons in addition to a checklist of items.
