### ISSUE TITLE
[Feature] Add index of item selected

### ISSUE THREAD

**Issue by hangocanh2303** [rushisangani/RSSelectionMenu#66]
I suggest you add index of item in selected callback function: selectionMenu.setSelectedItems(items: repetitionTypeSelectedArray) { (text, isSelected, selectedItems) in
i believe it can help this library better

**Comment by rushisangani** [comment]
@hangocanh2303 update to the latest version 6.0 and you will get selected index along with other parameters in callback.

```
selectionMenu.setSelectedItems(items: simpleSelectedArray) { [weak self] (item, index, isSelected, selectedItems) in

    // update your existing array with updated selected items, so when menu show menu next time, updated items will be default selected.
    self?.simpleSelectedArray = selectedItems
}
```
Some new features are also added like 'EmptyData message', 'Checkbox style'.
Thanks 👍

**Comment by hangocanh2303** [comment]
Many thanks @rushisangani, you are the best 👍
