### ISSUE TITLE
error in buttuns

### ISSUE THREAD

**Issue by Amirnajafi** [rushisangani/RSSelectionMenu#7]
i don't know why in new update my buttons (navigations button and search cancel button ) not showing up at all 
in my code i setup 

selectionMenu.rightBarButtonTitle = "Submit"
selectionMenu.leftBarButtonTitle = "Close"

and for my search i setup 
selectionMenu.searchBarCancelButtonAttributes = SearchBarCancelButtonAttributes("Dismiss", .red)

and i want to customize search placeholder alignment in my case its stick on right but my language is RTL 
![screen shot 1396-08-06 at 12 05 46 pm](https://user-images.githubusercontent.com/7419126/32132860-af593e04-bbd8-11e7-92c7-9f2b2ec82c5f.png)

thank you for your support

**Comment by rushisangani** [comment]
@Amirnajafi 
I guess you've done something wrong.
Try this code, since it's perfectly working.

        // create menu
        let selectionMenu = RSSelectionMenu(selectionType: .Multiple, dataSource: dataArray) { (cell, object, indexPath) in
            cell.textLabel?.text = object
        }
        
        // set selected items
        selectionMenu.setSelectedItems(items: selectedArray) { (text, selected, selectedItems) in
            self.selectedArray = selectedItems
        }
        
        // show search bar
        selectionMenu.showSearchBar(withPlaceHolder: "Search Player", tintColor: UIColor.white.withAlphaComponent(0.4)) { (searchText) -> ([String]) in
            
            return self.dataArray.filter({ (player) -> Bool in
                return player.lowercased().hasPrefix(searchText.lowercased())
            })
        }
        
        // set navigation bar tintcolor and title color
        selectionMenu.setNavigationBar(title: "Select Player", attributes: [NSAttributedStringKey.foregroundColor.rawValue : UIColor.white], barTintColor: UIColor.orange.withAlphaComponent(0.6))
        
        // bar buttons
        selectionMenu.leftBarButtonTitle = "Close"
        selectionMenu.rightBarButtonTitle = "Submit"
        
        // cancel button attributes
        selectionMenu.searchBarCancelButtonAttributes = SearchBarCancelButtonAttributes("Dismiss", UIColor.darkGray)
     
        // show menu
        selectionMenu.show(from: self)

Here, left bar button will be shown only if, presentation style is **.present** and selection style is **single**.
Other it won't require left bar button.
