### ISSUE TITLE
An alphabetized index for fast picking in a long list?

### ISSUE THREAD

**Issue by ghubaddole** [rushisangani/RSSelectionMenu#70]
This is great Menu!!

I have a rather long list to show in the RSSelectionMenu and it'll be fabulous if you can add a feature for  an alphabetized index like https://github.com/mindz-eye/MYTableViewIndex!

Also, if we can add a small circular image on the left, it'll be the cherry on the cake!

Thanks, and happy new year! 
g

**Comment by rushisangani** [comment]
@ghubaddole Happy New Year 🥇 
you can use custom table view cells for design customization (circular image on the left). Please read doc for the same.

Sure I'll try to add TableViewIndexing feature for upcoming release. Meanwhile you can use SearchBar to quickly search an item from the long list.

Thanks again :)
