### ISSUE TITLE
Change selection on air

### ISSUE THREAD

**Issue by juanm4** [rushisangani/RSSelectionMenu#71]
Hi, I would like to know how can I select/deselect items programatically when RSSelectionMenu is showing. I mean, for example, when I select the first item, I want deselect all other items automatically. 
The same should happens on the inverse situation, if I select one of items (except first) I want to deselect the first item.

I achieve that but only when RSSelectionMenu is closed and reopened again. So, I would like to get this  without the need to close the RSSelectionMenu.

Thanks in advance!!!

**Comment by rushisangani** [comment]
If your menu is the single selection you can use following.
`selectionMenu.dismissAutomatically = false`

Let me know if it's working for you.

**Comment by rushisangani** [comment]
@juanm4 Did you try this?

**Comment by juanm4** [comment]
Hi, I have tried this but it doesn't work, maybe because is not exactly the operating I looking for. I'm going to be more specific.

Imagine next select:
![captura de pantalla_2019-01-10_11-04-40](https://user-images.githubusercontent.com/4191613/50961297-9dccc180-14c7-11e9-9d63-fc2be2dd0c66.png)

And I want next function.
- If I select first option all other Values must be deselected
- If I select one or more Values the first option must be deselected (multiple selection for all of them except for the first option)

I supose that I am looking for a selection half simple and half multiple. If I could simulate a click event for one cell, I would get what I want.


`
selectionMenu.setSelectedItems(items: selectedDataArray, maxSelected: 3) { (item, selected, selectedItems) in
    // I want simulate click for cell here!
}
`

thanks!

**Comment by juanm4** [comment]
Great!! It was in front of me and I didn't realize that.
Thanks for your time!
