### ISSUE TITLE
Multiple Columns?

### ISSUE THREAD

**Issue by goalguy10** [rushisangani/RSSelectionMenu#72]
Is it possible for one RSSelectionMenu to have multiple columns? What I am trying to achieve is something like the datepicker but using RSSelectionMenu. I am looking to have 3 columns, each with different size arrays and each single selection.

**Comment by rushisangani** [comment]
@goalguy10
Nope this is not possible.

**Comment by goalguy10** [comment]
@rushisangani 
I was afraid of that. Any chance of this being added to an update?

**Comment by rushisangani** [comment]
@goalguy10 
Multi-columns is a totally different approach for this drop-down/selection menu.
You should rather use picker for that.

Or if you want to use RSSelectionMenu, then you should put 3 buttons side by side and show this menu as a popover from that.

Perhaps you can consider to change that multi-column approach to multiple dropdowns and show them one-by-one, like country then state then city dropdown.

Hope this helps.
