### ISSUE TITLE
It is possible to dismiss the alert controller without going through the dismiss handler?

### ISSUE THREAD

**Issue by WBiOSD111** [rushisangani/RSSelectionMenu#77]
I love the menu by the way! 

I was curious to know if it would be possible to dismiss the alert controller without going through the dismiss handler.  I don't what to have anything saved to the selected array when the user clicks on the outside of the alert controller.

**Comment by rushisangani** [comment]
@WBiOSD111 thank you for using this :)
I am not correctly getting your problem. What should happen, if there are already items selected while presenting the menu and a user clicks outside the menu?

**Comment by WBiOSD111** [comment]
In my case, the user selects items and then click "Done" to saved them.  Is there any way to avoid having this same behavior when the user clicks outside the menu? In other words, only dismiss the alert controller without saving the selected items.  Let me know if that makes more sense.

**Comment by rushisangani** [comment]
@WBiOSD111 For the presentation style **ActionSheet**, if you've specified the "Done" button.
AlertController will be automatically dismissed when tapping outside, which is similar to clicking on a done button.
I don't think so, we have a way to find out whether it's clicking on Done or outside.

What your thoughts on this.
