### ISSUE TITLE
leftBarButton with .present and multiple selection

### ISSUE THREAD

**Issue by goalguy10** [rushisangani/RSSelectionMenu#78]
The leftBarButton is not showing when I am presenting a multiple selection list with .present. Is this the correct behavior? If so, is it possible to add a leftBarButton? I am looking to add a cancel button.

Also, is it possible to change the rightBarButton text once the user starts selecting items? I have tried to set .rightBarButtonTitle within the .setSelectedItems function but the rightBarButtonTitle does not change.

**Comment by rushisangani** [comment]
Hi, @goalguy10 **.present** style should by default show cancel button.
Can you please share your code?

**Comment by rushisangani** [comment]
@goalguy10 You can set `menu.rightBarButtonTitle = ""`.
Let me know if that works?

**Comment by goalguy10** [comment]
> Hi, @goalguy10 **.present** style should by default show cancel button.
> Can you please share your code?

The only button showing is the .rightBarButton.
```
let officerMenu = RSSelectionMenu(selectionStyle: .multiple, dataSource: testOfficerArray) {
            (cell, object, indexPath) in
            cell.textLabel?.text = object
        }
        
        officerMenu.setSelectedItems(items: selectedOfficerArray) { [weak self] (item, index, isSelected, selectedItems) in
            print("Set Selected")
            officerMenu.rightBarButtonTitle = "Save"
            self?.selectedOfficerArray = selectedItems
        }
        
        officerMenu.showSearchBar { (searchText) -> ([String]) in
            return self.selectedOfficerArray.filter({ $0.lowercased().contains(searchText.lowercased()) })
        }
        
        officerMenu.addFirstRowAs(rowType: .none, showSelected: self.firstRowSelected) { (text, isSelected) in
            self.firstRowSelected = isSelected
            officerMenu.rightBarButtonTitle = "Save"
        }
        
        officerMenu.onDismiss = { selectedItems in
            self.selectedOfficerArray = selectedItems
            print(self.selectedOfficerArray.count)
            self.selectedIndex = 0
        }
        
        officerMenu.cellSelectionStyle = .checkbox
        officerMenu.title = "Please Select Your Partner(s)"
        officerMenu.rightBarButtonTitle = "Done"
        
        officerMenu.show(style: .present, from: self)
    }
```

The:
```
officerMenu.setSelectedItems(items: selectedOfficerArray) { [weak self] (item, index, isSelected, selectedItems) in
            print("Set Selected")
            officerMenu.rightBarButtonTitle = "Save"
            self?.selectedOfficerArray = selectedItems
        }
```
code does not change the rightBarButtonTitle when I start selecting items.

**Comment by rushisangani** [comment]
Hey @goalguy10 for multi-selection, there will not be any leftBarButton. It's because if we put cancel in it, there would be an ambiguity whether to discard user's existing selection or not.

let's say, a user has passed 5 items as already selected, and now added few more items and removed few items, now clicking on cancel button will make the scenario complicated whether to discard all of them or keeping earlier one.
So only 'Done' button allows the final choice of selection, to make it more simplistic.

**Comment by rushisangani** [comment]
@goalguy10 I'll surely look into the barButtonItem title change.
