### ISSUE TITLE
Localization FirstRowType Value

### ISSUE THREAD

**Issue by hstdt** [rushisangani/RSSelectionMenu#8]
Now we can't customize the value of `FirstRowType.None` &  `FirstRowType.All`.

![image](https://user-images.githubusercontent.com/10215098/33057098-0e553626-cec4-11e7-9e84-add506420ef8.png)

**Comment by rushisangani** [comment]
Hello, @hstdt upgrade your pod to the latest version 2.0.9 and you'll be able to use custom strings as FirstRowType.

**Comment by hstdt** [comment]
@rushisangani  Thanks, it works.
