### ISSUE TITLE
Support Pagination 

### ISSUE THREAD

**Issue by X901** [rushisangani/RSSelectionMenu#83]
Hi ,
this framework is great for making forms in iOS

but it missing Pagination 
when there is alot of data only display frist 10 from example 
and every time user scrolling down it will display more cells

this fremwork is do the job
https://github.com/salmaanahmed/PaginatedTableView

it will good to have it on this fremwork !

**Comment by rushisangani** [comment]
@X901 Thanks for the suggestion. I will surely try to integrate if possible.
