### ISSUE TITLE
way to embed the menu in a view controller as opposed to a modal

### ISSUE THREAD

**Issue by ghubaddole** [rushisangani/RSSelectionMenu#84]
Can you tell me if it is possible to embed the menu in a view controller either via storyboard or programmatically, rather than presenting it as a modal?

**Comment by rushisangani** [comment]
@ghubaddole It's not possible as of now, you should use **actionsheet** or **alert** menu presentation style for that.

**Comment by ghubaddole** [comment]
Alternately, if the menu can be presented like an ios 13 style action sheet (even on ios 12), that'll be great.
