### ISSUE TITLE
how can I add sections ?

### ISSUE THREAD

**Issue by X901** [rushisangani/RSSelectionMenu#85]
Hi , 
is this library support sections ?
I only need sections to organize my data

so the User can see the data organized
but the selected items will be in only on array

I see the Demo video and see all the tableview is default tableview without the sections
so I wonder is it possible to do it using the library ?

like :

A
-------------
a0  ✔️
a1
a2  ✔️

B
-------------
b0  ✔️
b1
b2

**Comment by rushisangani** [comment]
@X901 It's not possible as of now, I will try to figure out If I can implement this.
Sections would be much more complicated than just showing Alphabet letters.
- It could be custom text
- The way we're passing data would also affect (simple array will not work).

**Comment by sourabhsharmait** [comment]
Is there any future plans to add section headers?
