### ISSUE TITLE
ios 11.2 formview bug

### ISSUE THREAD

**Issue by Amirnajafi** [rushisangani/RSSelectionMenu#9]
in ios 11.2 formview viewing with bug you cant see it int picute 
![screen shot 1396-09-19 at 12 20 26 pm](https://user-images.githubusercontent.com/7419126/33803403-af82001c-dda4-11e7-9e5f-e7762821d4fd.png)

**Comment by rushisangani** [comment]
Hello @Amirnajafi, Could you please share your code that how you're presenting the menu.
So that I can try to resolve it asap.

Thanks.

**Comment by Amirnajafi** [comment]
let selectionMenu =  RSSelectionMenu(dataSource: educationLvlElement) { (cell, object, indexPath) in
			ConfigSelectionCell(cell: cell)
			cell.textLabel?.text = object
		}
		
		selectionMenu.tableView?.semanticContentAttribute  = .forceRightToLeft
		selectionMenu.setSelectedItems(items: selectedField) { (text, isSelected, selectedItems) in
			self.selectedEducatinLvl = selectedItems
			self.educationLvlLabel.text = text
			
		}
		
		selectionMenu.showSearchBar(withPlaceHolder: "جستجو", tintColor: UIColor.white) { (Text) -> ([String]) in
			return self.educationLvlElement.filter({ $0.contains(Text)})
		}

		if IsIpad() {
			selectionMenu.show(style: .Popover(sourceView: educationLvlLabel, size: nil), from: self)
		}else{
			selectionMenu.show(style: .Formsheet, from: self)
		}

**Comment by Amirnajafi** [comment]
in mobile of tablet in formsheet view my form go to the bottom down of page

**Comment by rushisangani** [comment]
Hi @Amirnajafi, this bug was due to iOS 11.2 layout changes.
This is fixed now in latest version **RSSelectionMenu (3.1)**
Also, the base version of swift is changed to 4.0

Kindly update your pod to get latest features and bug fixes.

**Comment by praditkan** [comment]
I have this problem on SplitView. (Master-Detail.)
It happens on the Detail screen.
