### ISSUE TITLE
For iOS13 .present need to provide option for fullscreen 

### ISSUE THREAD

**Issue by kishore94** [rushisangani/RSSelectionMenu#93]
if case .present = with {
            tobePresentController = UINavigationController(rootViewController: self)
            tobePresentController.modalPresentationStyle = . overCurrentContext // added this line but still not presenting as fullscreen. 
        }

**Comment by rushisangani** [comment]
@kishore94 use tobePresentController.modalPresentationStyle = . fullScreen
