### ISSUE TITLE
Popover dismiss on click not working

### ISSUE THREAD

**Issue by aryan-smartsense** [rushisangani/RSSelectionMenu#94]
Hi, I'm unable to dismiss the popover presentation in multiple selection type. Earlier, it used to dismiss itself on touch outside the popover window. Single selection is working fine as of now since it must be dismissing onSelect.
iOS version: 13.3
pod version: 6.1.0
This is the code that I'm using:

    guard let viewModel = self.viewModel, let options = viewModel.options else { return }
        
	let menu = RSSelectionMenu(selectionStyle: viewModel.selectionType, dataSource: options) { (cell, item, indexPath) in
        cell.textLabel?.text = item.optionValue
    }
        
	menu.setSelectedItems(items: selectedOptions) { [weak self] (selectedOption, isSelected, _, selectedOptions)  in
        self?.selectedOptions = selectedOptions
        self?.viewModel?.selectedOptions = selectedOptions
        self?.updateView()
    }
		
    menu.show(style: .popover(sourceView: self.contentView, size: nil), from: self.parentContainerViewController() ?? Utils.getTopVC()!)
        
    menu.onDismiss = { [weak self] selectedItems in
	     self?.textField.text = selectedItems.map({ $0.optionValue! }).joined(separator: ", ")
         self?.textField.resignFirstResponder()
     }

Please point me in the right direction

**Comment by rushisangani** [comment]
Hi @aryan-smartsense 
I need to check this.

But I suggest you use another style for multiple selection either formsheet or actionSheet.
Because it’s better to have user’s confirmation after selecting multiple rows, which can be achieved by ‘Done’ button.

Let me know that helps :)
Meanwhile I will check how it should work for Multiple selection for Poppver style.

**Comment by aryan-smartsense** [comment]
Hi @rushisangani 
I've started using actionSheet for now.
Still, keep posted until popover starts to work again as expected.

Thanks
