### ISSUE TITLE
Could not cast value of type 'Project.ServicesType' (0x11071c9d0) to 'NSObject' (0x111cecd70).

### ISSUE THREAD

**Issue by harish3737** [rushisangani/RSSelectionMenu#96]
struct ServicesType : Mappable, UniquePropertyDelegate {
    func getUniquePropertyName() -> String {
        return "id"
    }
    
    var id : Int?
    var name : String?
    var description : String?
    var image : String?

    init?(map: Map) {

    }

    mutating func mapping(map: Map) {

        id <- map["id"]
        name <- map["name"]
        description <- map["description"]
        image <- map["image"]
    }

}

func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        if textField == textFieldSpeciality{
            let menu = RSSelectionMenu(selectionStyle: .multiple, dataSource: speciality ?? []) { (cell, name, indexPath) in
                cell.textLabel?.text = name.name ?? ""
                
                
            }
            
            menu.setSelectedItems(items: specialitySelector) { (name, index, selected, selectedItems) in
                self.specialitySelector = selectedItems
          }
            
            menu.show(from: self)
            return false
        }
        else{
            return true
        }
    }

**Comment by harish3737** [comment]
I am not getting a value for the same when I  use codable,while running the value I am facing the following error,I am getting the value from an api and using it as same

**Comment by rushisangani** [comment]
@harish3737 You can fix this by only passing string array to the RSSelectionMenu as DataSource.
You need to map like below.

`let dataSource = serviceTypes.map { $0.name }` 
You will get selected names afterwards. 

Then if you need serviceType object again you can check for 
`serviceTypes.first { $0.name == selectName }`

OR
 
You can create another temperory struct like below
```
struct ServiceTypeSelectable: Codable, UniquePropertyDelegate {
    let id : Int
    let name: Int

    func getUniquePropertyName() -> String {
        return "id"
    }
}
```
You can pass array of above structs as DataSource, like below;
`let dataSource = serviceTypes.map { ServiceTypeSelectable(id: $0.id, name: $0.name) }`

**Comment by rushisangani** [comment]
For Strings type of array, you don't need to set UniquePropertyDelegate.
