### ISSUE TITLE
It takes 11+ minutes for FormSelectionMenu to popup...

### ISSUE THREAD

**Issue by praditkan** [rushisangani/RSSelectionMenu#98]
I have 4 ViewControllers embedded in NavigationController.
The 4th view I call FormSelectionMenu it works.
But either I wait for 11+ minutes or I touch 2nd tap on the screen then
the menu will show up.

However, in order for me to make this to work, I have to put these in my AppDelegate.
Otherwise, the window will always be nil.

> I'm supporting iOS 9.0 with iPAD.

     'self.window = UIWindow(frame: UIScreen.main.bounds)
     let mainVC = UIViewController()
     self.window?.rootViewController = mainVC
     self.window?.makeKeyAndVisible()'

I mostly copy and paste your example code only part that I need for the FormSelectionMenu.

Please help advise.

**Comment by praditkan** [comment]
I found my TableViewCell > Selection > None.
Then I changed to Selection > Default.
It's working as it should be now.
Thanks.

However, the window is nil am I doing it right?

**Comment by rushisangani** [comment]
@praditkan is this worked for you?
If so, please close this issue.
